Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 14
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	calc_integrals_dim2
	1	clean_data
	1	make_plots
	1	pade_approx
	1	plot_cumulants
	1	plot_sfs
	7

[Wed Oct 12 09:06:32 2022]
rule calc_integrals_dim2:
    output: spatial_integrals_dim2.csv
    jobid: 5

/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/scipy/integrate/quadpack.py:880: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  **opt)
/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/scipy/integrate/quadpack.py:880: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  **opt)
calculating u2 (2D)
calculating u3 (2D)
[Fri Oct 14 19:19:24 2022]
Finished job 5.
1 of 7 steps (14%) done

[Fri Oct 14 19:19:24 2022]
rule plot_cumulants:
    input: spatial_integrals_dim1.csv, spatial_integrals_dim2.csv
    output: cumulants_dim1.png, cumulants_dim2.png
    jobid: 2


[Fri Oct 14 19:19:25 2022]
rule pade_approx:
    input: spatial_integrals_dim1.csv, spatial_integrals_dim2.csv
    output: pade_approx_dim1_errorFalse.csv, pade_approx_dim1_errorTrue.csv, pade_approx_dim2_errorFalse.csv, pade_approx_dim2_errorTrue.csv
    jobid: 7

[Fri Oct 14 19:19:35 2022]
Finished job 2.
2 of 7 steps (29%) done
[Fri Oct 14 19:19:53 2022]
Finished job 7.
3 of 7 steps (43%) done

[Fri Oct 14 19:19:53 2022]
rule clean_data:
    input: pade_approx_dim1_errorFalse.csv, pade_approx_dim1_errorTrue.csv, pade_approx_dim2_errorFalse.csv, pade_approx_dim2_errorTrue.csv
    output: cleaned_data_dim1_errorFalse.csv, cleaned_data_dim1_errorTrue.csv, cleaned_data_dim2_errorFalse.csv, cleaned_data_dim2_errorTrue.csv
    jobid: 4

[Fri Oct 14 19:20:00 2022]
Finished job 4.
4 of 7 steps (57%) done

[Fri Oct 14 19:20:00 2022]
rule plot_sfs:
    input: cleaned_data_dim1_errorFalse.csv, cleaned_data_dim2_errorFalse.csv
    output: plots_sfs_dim1_polytype_2_1_N10000.png, plots_params_selection_dim1_polytype_2_1_N10000.png, plots_sfs_dim2_polytype_1_1_N1000.png, plots_params_selection_dim2_polytype_1_1_N1000.png
    jobid: 3


[Fri Oct 14 19:20:00 2022]
rule make_plots:
    input: cleaned_data_dim1_errorFalse.csv, cleaned_data_dim1_errorTrue.csv, cleaned_data_dim2_errorFalse.csv, cleaned_data_dim2_errorTrue.csv
    output: plots_pade_poles_dim1_errorTrue.png, plots_pade_poles_dim1_errorFalse.png, plots_pade_residues_dim1_errorTrue.png, plots_pade_residues_dim1_errorFalse.png, plots_pade_remainder_dim1_errorTrue.png, plots_pade_remainder_dim1_errorFalse.png, plots_pade_poles_vs_residues_dim1_errorTrue.png, plots_pade_poles_vs_residues_dim1_errorFalse.png, plots_pade_error_dim1_errorTrue.png, plots_pade_rel_error_dim1_errorTrue.png, plots_pade_pole_error_dim1_errorTrue.png, plots_pade_poles_dim2_errorTrue.png, plots_pade_poles_dim2_errorFalse.png, plots_pade_residues_dim2_errorTrue.png, plots_pade_residues_dim2_errorFalse.png, plots_pade_remainder_dim2_errorTrue.png, plots_pade_remainder_dim2_errorFalse.png, plots_pade_poles_vs_residues_dim2_errorTrue.png, plots_pade_poles_vs_residues_dim2_errorFalse.png, plots_pade_error_dim2_errorTrue.png, plots_pade_rel_error_dim2_errorTrue.png, plots_pade_pole_error_dim2_errorTrue.png
    jobid: 1

/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning
/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning
Traceback (most recent call last):
  File "make_plots_pade.py", line 70, in <module>
    main()
  File "make_plots_pade.py", line 39, in main
    xtrans='log',ytrans='symlog',linthreshy=1e-1)
  File "make_plots_pade.py", line 11, in plot_scatter
    plt.yscale(ytrans,linthreshy=linthreshy)
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/matplotlib/pyplot.py", line 3067, in yscale
    return gca().set_yscale(value, **kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 4117, in set_yscale
    ax.yaxis._set_scale(value, **kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/matplotlib/axis.py", line 761, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/lib/python3.7/site-packages/matplotlib/scale.py", line 597, in scale_factory
    return scale_cls(axis, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'linthreshy'
[Fri Oct 14 19:20:16 2022]
Error in rule make_plots:
    jobid: 1
    output: plots_pade_poles_dim1_errorTrue.png, plots_pade_poles_dim1_errorFalse.png, plots_pade_residues_dim1_errorTrue.png, plots_pade_residues_dim1_errorFalse.png, plots_pade_remainder_dim1_errorTrue.png, plots_pade_remainder_dim1_errorFalse.png, plots_pade_poles_vs_residues_dim1_errorTrue.png, plots_pade_poles_vs_residues_dim1_errorFalse.png, plots_pade_error_dim1_errorTrue.png, plots_pade_rel_error_dim1_errorTrue.png, plots_pade_pole_error_dim1_errorTrue.png, plots_pade_poles_dim2_errorTrue.png, plots_pade_poles_dim2_errorFalse.png, plots_pade_residues_dim2_errorTrue.png, plots_pade_residues_dim2_errorFalse.png, plots_pade_remainder_dim2_errorTrue.png, plots_pade_remainder_dim2_errorFalse.png, plots_pade_poles_vs_residues_dim2_errorTrue.png, plots_pade_poles_vs_residues_dim2_errorFalse.png, plots_pade_error_dim2_errorTrue.png, plots_pade_rel_error_dim2_errorTrue.png, plots_pade_pole_error_dim2_errorTrue.png

RuleException:
CalledProcessError in line 125 of /project2/jnovembre/steinerm/rvsfs/spatial-sfs/theory/numerics_snakemake/Snakefile:
Command ' set -euo pipefail;  
        python make_plots_pade.py --dim 1
        python make_plots_pade.py --dim 1 --calc_error
        python make_plots_pade.py --dim 2
        python make_plots_pade.py --dim 2 --calc_error ' returned non-zero exit status 1.
  File "/project2/jnovembre/steinerm/rvsfs/spatial-sfs/theory/numerics_snakemake/Snakefile", line 125, in __rule_make_plots
  File "/home/steinerm/.conda/envs/snakemake/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job make_plots since they might be corrupted:
plots_pade_poles_dim1_errorFalse.png
Waiting at most 5 seconds for missing files.
MissingOutputException in line 132 of /project2/jnovembre/steinerm/rvsfs/spatial-sfs/theory/numerics_snakemake/Snakefile:
Missing files after 5 seconds:
plots_sfs_dim2_polytype_1_1_N1000.png
plots_params_selection_dim2_polytype_1_1_N1000.png
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Removing output files of failed job plot_sfs since they might be corrupted:
plots_sfs_dim1_polytype_2_1_N10000.png, plots_params_selection_dim1_polytype_2_1_N10000.png
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /project2/jnovembre/steinerm/rvsfs/spatial-sfs/theory/numerics_snakemake/.snakemake/log/2022-10-12T090632.649477.snakemake.log
